version: '3.1'

services:

  customer-service:
    build: ./customer-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"

  account-service:
    build: ./account-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"