// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/account/account.proto

package account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Customer struct {
	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	//repeated fields are used for arrays or list
	//multiple addresses
	Addresses            []*Address `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	PhoneNumbers         []string   `protobuf:"bytes,5,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	EmailAddress         string     `protobuf:"bytes,6,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{1}
}

func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (m *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(m, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Customer) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Customer) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Customer) GetAddresses() []*Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *Customer) GetPhoneNumbers() []string {
	if m != nil {
		return m.PhoneNumbers
	}
	return nil
}

func (m *Customer) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

//TODO these can be imported
//Address type
type Address struct {
	AddressLine_1        string   `protobuf:"bytes,1,opt,name=address_line_1,json=addressLine1,proto3" json:"address_line_1,omitempty"`
	AddressLine_2        string   `protobuf:"bytes,2,opt,name=address_line_2,json=addressLine2,proto3" json:"address_line_2,omitempty"`
	ZipCode              string   `protobuf:"bytes,3,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	City                 string   `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Country              string   `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{2}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAddressLine_1() string {
	if m != nil {
		return m.AddressLine_1
	}
	return ""
}

func (m *Address) GetAddressLine_2() string {
	if m != nil {
		return m.AddressLine_2
	}
	return ""
}

func (m *Address) GetZipCode() string {
	if m != nil {
		return m.ZipCode
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type Response struct {
	Customer             *Customer `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	Created              bool      `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func init() {
	proto.RegisterType((*Account)(nil), "account.Account")
	proto.RegisterType((*Customer)(nil), "account.Customer")
	proto.RegisterType((*Address)(nil), "account.Address")
	proto.RegisterType((*Response)(nil), "account.Response")
}

func init() { proto.RegisterFile("proto/account/account.proto", fileDescriptor_5d492a0187472a3b) }

var fileDescriptor_5d492a0187472a3b = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcd, 0x6e, 0xe2, 0x30,
	0x10, 0xc7, 0x09, 0x01, 0x92, 0x0c, 0x2c, 0xda, 0xf5, 0xc9, 0xbb, 0x68, 0x25, 0x94, 0xf6, 0xc0,
	0xa1, 0xd0, 0x92, 0x3e, 0x01, 0xe2, 0xd0, 0x4b, 0xc5, 0x21, 0x3c, 0x40, 0x14, 0x92, 0xa9, 0x6a,
	0x89, 0xc4, 0x91, 0x1d, 0x2a, 0xc1, 0xc3, 0xf4, 0x99, 0xfa, 0x48, 0x55, 0x26, 0x36, 0x20, 0xd1,
	0x53, 0x66, 0x7e, 0xf3, 0x9f, 0xc9, 0x7c, 0x18, 0x26, 0x95, 0x92, 0xb5, 0x7c, 0x4c, 0xb3, 0x4c,
	0x1e, 0xca, 0xda, 0x7e, 0x17, 0x44, 0x99, 0x67, 0xdc, 0x70, 0x0e, 0xde, 0xaa, 0x35, 0xd9, 0x18,
	0xba, 0x22, 0xe7, 0xce, 0xd4, 0x99, 0x05, 0x71, 0x57, 0xe4, 0x8c, 0x41, 0xaf, 0x4c, 0x0b, 0xe4,
	0x5d, 0x22, 0x64, 0x87, 0x5f, 0x0e, 0xf8, 0xeb, 0x83, 0xae, 0x65, 0x81, 0xea, 0x26, 0xe1, 0x3f,
	0xc0, 0x9b, 0x50, 0xba, 0x4e, 0xae, 0xd2, 0x02, 0x22, 0x9b, 0xb4, 0x40, 0x36, 0x81, 0x60, 0x9f,
	0xda, 0xa8, 0x4b, 0x51, 0xbf, 0x01, 0x14, 0x5c, 0x40, 0x90, 0xe6, 0xb9, 0x42, 0xad, 0x51, 0xf3,
	0xde, 0xd4, 0x9d, 0x0d, 0xa3, 0xdf, 0x0b, 0xdb, 0xf3, 0xaa, 0x8d, 0xc4, 0x17, 0x09, 0xbb, 0x83,
	0x5f, 0xd5, 0xbb, 0x2c, 0x31, 0x29, 0x0f, 0xc5, 0x0e, 0x95, 0xe6, 0xfd, 0xa9, 0x3b, 0x0b, 0xe2,
	0x11, 0xc1, 0x4d, 0xcb, 0x1a, 0x11, 0x16, 0xa9, 0xd8, 0x27, 0x26, 0x8f, 0x0f, 0xe8, 0xaf, 0x23,
	0x82, 0xa6, 0x68, 0xf8, 0xe9, 0x80, 0x67, 0x6c, 0x76, 0x0f, 0x63, 0x23, 0x4d, 0xf6, 0xa2, 0xc4,
	0x64, 0x69, 0xa6, 0x1b, 0x19, 0xfa, 0x2a, 0x4a, 0x5c, 0xde, 0xa8, 0x22, 0x33, 0xeb, 0xb5, 0x2a,
	0x62, 0x7f, 0xc1, 0x3f, 0x89, 0x2a, 0xc9, 0x64, 0x6e, 0xa7, 0xf5, 0x4e, 0xa2, 0x5a, 0xcb, 0x1c,
	0x9b, 0xcd, 0x66, 0xa2, 0x3e, 0xf2, 0x5e, 0xbb, 0xd9, 0xc6, 0x66, 0x1c, 0x3c, 0x1a, 0x56, 0x1d,
	0x79, 0xbf, 0x55, 0x1b, 0x37, 0xdc, 0x82, 0x1f, 0xa3, 0xae, 0x64, 0xa9, 0x91, 0xcd, 0xc1, 0xcf,
	0xcc, 0xfa, 0xa9, 0xb5, 0x61, 0xf4, 0xe7, 0xbc, 0x25, 0x7b, 0x97, 0xf8, 0x2c, 0xa1, 0xa2, 0x0a,
	0xd3, 0x1a, 0x73, 0x6a, 0xd1, 0x8f, 0xad, 0x1b, 0x55, 0x30, 0x36, 0x77, 0xdf, 0xa2, 0xfa, 0x10,
	0x19, 0xb2, 0x27, 0x18, 0xac, 0x29, 0xc8, 0x6e, 0x4b, 0xfe, 0xbb, 0x20, 0xdb, 0x4a, 0xd8, 0x61,
	0x0f, 0xe0, 0xbe, 0x60, 0xfd, 0x93, 0xfc, 0xea, 0x74, 0xe6, 0x9d, 0x75, 0x76, 0x03, 0x7a, 0x79,
	0xcf, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x88, 0xdf, 0xc0, 0xa5, 0x98, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AccountService service

type AccountServiceClient interface {
	Create(ctx context.Context, in *Customer, opts ...client.CallOption) (*Response, error)
	Get(ctx context.Context, in *Customer, opts ...client.CallOption) (*Account, error)
}

type accountServiceClient struct {
	c           client.Client
	serviceName string
}

func NewAccountServiceClient(serviceName string, c client.Client) AccountServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "account"
	}
	return &accountServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *accountServiceClient) Create(ctx context.Context, in *Customer, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "AccountService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Get(ctx context.Context, in *Customer, opts ...client.CallOption) (*Account, error) {
	req := c.c.NewRequest(c.serviceName, "AccountService.Get", in)
	out := new(Account)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AccountService service

type AccountServiceHandler interface {
	Create(context.Context, *Customer, *Response) error
	Get(context.Context, *Customer, *Account) error
}

func RegisterAccountServiceHandler(s server.Server, hdlr AccountServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&AccountService{hdlr}, opts...))
}

type AccountService struct {
	AccountServiceHandler
}

func (h *AccountService) Create(ctx context.Context, in *Customer, out *Response) error {
	return h.AccountServiceHandler.Create(ctx, in, out)
}

func (h *AccountService) Get(ctx context.Context, in *Customer, out *Account) error {
	return h.AccountServiceHandler.Get(ctx, in, out)
}
