// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/customer/customer.proto

package customerpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Customer struct {
	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	//repeated fields are used for arrays or list
	//multiple addresses
	Addresses            []*Address `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	PhoneNumbers         []string   `protobuf:"bytes,5,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	EmailAddress         string     `protobuf:"bytes,6,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_315a25ac42c245d7, []int{0}
}

func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (m *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(m, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Customer) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Customer) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Customer) GetAddresses() []*Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *Customer) GetPhoneNumbers() []string {
	if m != nil {
		return m.PhoneNumbers
	}
	return nil
}

func (m *Customer) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

//TODO these can be imported
//Address type
type Address struct {
	AddressLine_1        string   `protobuf:"bytes,1,opt,name=address_line_1,json=addressLine1,proto3" json:"address_line_1,omitempty"`
	AddressLine_2        string   `protobuf:"bytes,2,opt,name=address_line_2,json=addressLine2,proto3" json:"address_line_2,omitempty"`
	ZipCode              string   `protobuf:"bytes,3,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	City                 string   `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Country              string   `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_315a25ac42c245d7, []int{1}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAddressLine_1() string {
	if m != nil {
		return m.AddressLine_1
	}
	return ""
}

func (m *Address) GetAddressLine_2() string {
	if m != nil {
		return m.AddressLine_2
	}
	return ""
}

func (m *Address) GetZipCode() string {
	if m != nil {
		return m.ZipCode
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

// Created a blank get request
type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_315a25ac42c245d7, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type Response struct {
	Created  bool      `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Customer *Customer `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	// Added a pluralised consignment to our generic response message
	// array of these types
	Customers            []*Customer `protobuf:"bytes,3,rep,name=customers,proto3" json:"customers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_315a25ac42c245d7, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *Response) GetCustomers() []*Customer {
	if m != nil {
		return m.Customers
	}
	return nil
}

func init() {
	proto.RegisterType((*Customer)(nil), "customer.Customer")
	proto.RegisterType((*Address)(nil), "customer.Address")
	proto.RegisterType((*GetRequest)(nil), "customer.GetRequest")
	proto.RegisterType((*Response)(nil), "customer.Response")
}

func init() { proto.RegisterFile("proto/customer/customer.proto", fileDescriptor_315a25ac42c245d7) }

var fileDescriptor_315a25ac42c245d7 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xb1, 0xce, 0xd3, 0x30,
	0x10, 0x80, 0x49, 0xd3, 0xff, 0x6f, 0x72, 0x0d, 0x45, 0x9c, 0x18, 0x0c, 0xa8, 0x52, 0x15, 0x18,
	0x3a, 0xb5, 0x34, 0x6c, 0xdd, 0xa0, 0x43, 0x17, 0xd4, 0x21, 0x6c, 0x2c, 0x51, 0x9a, 0x1c, 0xc2,
	0x52, 0x13, 0x07, 0xdb, 0x41, 0x6a, 0x1f, 0x00, 0x89, 0x97, 0xe0, 0x9d, 0x78, 0x23, 0x54, 0xc7,
	0x4e, 0x2a, 0xfd, 0xdd, 0xee, 0xbe, 0xfb, 0xce, 0xf1, 0xe5, 0x0c, 0xf3, 0x46, 0x0a, 0x2d, 0xd6,
	0x45, 0xab, 0xb4, 0xa8, 0x48, 0xf6, 0xc1, 0xca, 0x70, 0x0c, 0x5c, 0x1e, 0xff, 0xf3, 0x20, 0xd8,
	0xd9, 0x04, 0x67, 0x30, 0xe2, 0x25, 0xf3, 0x16, 0xde, 0x32, 0x4c, 0x47, 0xbc, 0xc4, 0x39, 0xc0,
	0x77, 0x2e, 0x95, 0xce, 0xea, 0xbc, 0x22, 0x36, 0x32, 0x3c, 0x34, 0xe4, 0x90, 0x57, 0x84, 0x6f,
	0x21, 0x3c, 0xe5, 0xae, 0xea, 0x9b, 0x6a, 0x70, 0x05, 0xa6, 0xb8, 0x86, 0x30, 0x2f, 0x4b, 0x49,
	0x4a, 0x91, 0x62, 0xe3, 0x85, 0xbf, 0x9c, 0x26, 0x2f, 0x57, 0xfd, 0x35, 0x3e, 0x75, 0xa5, 0x74,
	0x70, 0xf0, 0x1d, 0x3c, 0x6f, 0x7e, 0x88, 0x9a, 0xb2, 0xba, 0xad, 0x8e, 0x24, 0x15, 0x7b, 0x58,
	0xf8, 0xcb, 0x30, 0x8d, 0x0c, 0x3c, 0x74, 0xec, 0x2a, 0x51, 0x95, 0xf3, 0x53, 0x66, 0xfb, 0xd8,
	0xa3, 0xf9, 0x6c, 0x64, 0xa0, 0x3d, 0x34, 0xfe, 0xeb, 0xc1, 0xc4, 0xc6, 0xf8, 0x1e, 0x66, 0x56,
	0xcd, 0x4e, 0xbc, 0xa6, 0x6c, 0x63, 0xc7, 0x8b, 0x2c, 0xfd, 0xc2, 0x6b, 0xda, 0x3c, 0xb1, 0x12,
	0x3b, 0xec, 0xad, 0x95, 0xe0, 0x6b, 0x08, 0x2e, 0xbc, 0xc9, 0x0a, 0x51, 0xba, 0x71, 0x27, 0x17,
	0xde, 0xec, 0x44, 0x49, 0x88, 0x30, 0x2e, 0xb8, 0x3e, 0xb3, 0xb1, 0xc1, 0x26, 0x46, 0x06, 0x93,
	0x42, 0xb4, 0xb5, 0x96, 0x67, 0xf6, 0xd0, 0xd9, 0x36, 0x8d, 0x23, 0x80, 0x3d, 0xe9, 0x94, 0x7e,
	0xb6, 0xa4, 0x74, 0xfc, 0xdb, 0x83, 0x20, 0x25, 0xd5, 0x88, 0x5a, 0x91, 0x69, 0x92, 0x94, 0x6b,
	0xea, 0xf6, 0x10, 0xa4, 0x2e, 0xc5, 0x15, 0xf4, 0x5b, 0x33, 0xb7, 0x9b, 0x26, 0x38, 0xfc, 0x4f,
	0xb7, 0xc2, 0xb4, 0x77, 0xf0, 0x03, 0x84, 0x2e, 0x56, 0xcc, 0x37, 0x0b, 0xb8, 0xd7, 0x30, 0x48,
	0xc9, 0x1f, 0x0f, 0x5e, 0x38, 0xfe, 0x95, 0xe4, 0x2f, 0x5e, 0x10, 0x6e, 0x61, 0xb6, 0x33, 0x17,
	0xe8, 0x1f, 0xc9, 0x9d, 0x43, 0xde, 0xdc, 0x30, 0x37, 0x49, 0xfc, 0x0c, 0xb7, 0x10, 0xed, 0x49,
	0x3b, 0x49, 0xe1, 0xab, 0xc1, 0x1a, 0xc6, 0xbf, 0xdf, 0xfb, 0x39, 0xfa, 0x06, 0x0e, 0x37, 0xc7,
	0xe3, 0xa3, 0x79, 0xb6, 0x1f, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x01, 0x91, 0xb8, 0xd7,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerServiceClient is the client API for CustomerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerServiceClient interface {
	CreateCustomer(ctx context.Context, in *Customer, opts ...grpc.CallOption) (*Response, error)
	// Created a new method
	GetCustomers(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error)
}

type customerServiceClient struct {
	cc *grpc.ClientConn
}

func NewCustomerServiceClient(cc *grpc.ClientConn) CustomerServiceClient {
	return &customerServiceClient{cc}
}

func (c *customerServiceClient) CreateCustomer(ctx context.Context, in *Customer, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/customer.CustomerService/CreateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) GetCustomers(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/customer.CustomerService/GetCustomers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServiceServer is the server API for CustomerService service.
type CustomerServiceServer interface {
	CreateCustomer(context.Context, *Customer) (*Response, error)
	// Created a new method
	GetCustomers(context.Context, *GetRequest) (*Response, error)
}

// UnimplementedCustomerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCustomerServiceServer struct {
}

func (*UnimplementedCustomerServiceServer) CreateCustomer(ctx context.Context, req *Customer) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomer not implemented")
}
func (*UnimplementedCustomerServiceServer) GetCustomers(ctx context.Context, req *GetRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomers not implemented")
}

func RegisterCustomerServiceServer(s *grpc.Server, srv CustomerServiceServer) {
	s.RegisterService(&_CustomerService_serviceDesc, srv)
}

func _CustomerService_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Customer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.CustomerService/CreateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).CreateCustomer(ctx, req.(*Customer))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_GetCustomers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).GetCustomers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.CustomerService/GetCustomers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).GetCustomers(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "customer.CustomerService",
	HandlerType: (*CustomerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCustomer",
			Handler:    _CustomerService_CreateCustomer_Handler,
		},
		{
			MethodName: "GetCustomers",
			Handler:    _CustomerService_GetCustomers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/customer/customer.proto",
}
